# Generated by Django 4.0.3 on 2022-04-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_artist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
