# Generated by Django 4.0.2 on 2022-04-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_artist_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='file',
        ),
    ]
